// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

var make = React.forwardRef((function (Props, ref_) {
        var id = Props.id;
        var heightProp = Props.heightProp;
        var match = id % 2 === 0;
        var tmp = {
          className: Css.style(/* :: */[
                Css.borderRadius(Css.px(8)),
                /* :: */[
                  Css.display(/* flex */-1010954439),
                  /* :: */[
                    Css.flexDirection(Css.row),
                    /* :: */[
                      Css.justifyContent(Css.center),
                      /* :: */[
                        Css.backgroundColor(match ? Css.hex("793698") : Css.hex("d6b4e7")),
                        /* :: */[
                          Css.height(Css.px(heightProp)),
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ])
        };
        var tmp$1 = Belt_Option.map((ref_ == null) ? undefined : Caml_option.some(ref_), (function (prim) {
                return prim;
              }));
        if (tmp$1 !== undefined) {
          tmp.ref = Caml_option.valFromOption(tmp$1);
        }
        return React.createElement("div", tmp, React.createElement("div", {
                        className: Css.style(/* :: */[
                              Css.display(/* flex */-1010954439),
                              /* :: */[
                                Css.flexDirection(Css.column),
                                /* :: */[
                                  Css.justifyContent(Css.center),
                                  /* :: */[
                                    Css.fontSize(Css.px(20)),
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ])
                      }, String(id)));
      }));

exports.make = make;
/* make Not a pure module */
