// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");

function Item(Props) {
  var id = Props.id;
  var match = id % 2 === 0;
  return React.createElement("div", {
              className: Css.style(/* :: */[
                    Css.borderRadius(Css.px(8)),
                    /* :: */[
                      Css.display(/* flex */-1010954439),
                      /* :: */[
                        Css.flexDirection(Css.row),
                        /* :: */[
                          Css.justifyContent(Css.center),
                          /* :: */[
                            Css.marginBottom(Css.px(8)),
                            /* :: */[
                              Css.marginTop(Css.px(8)),
                              /* :: */[
                                Css.backgroundColor(match ? Css.hex("793698") : Css.hex("d6b4e7")),
                                /* :: */[
                                  Css.height(Css.px(200)),
                                  /* [] */0
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ])
            }, React.createElement("div", {
                  className: Css.style(/* :: */[
                        Css.display(/* flex */-1010954439),
                        /* :: */[
                          Css.flexDirection(Css.column),
                          /* :: */[
                            Css.justifyContent(Css.center),
                            /* :: */[
                              Css.fontSize(Css.px(20)),
                              /* [] */0
                            ]
                          ]
                        ]
                      ])
                }, String(id)));
}

var make = Item;

exports.make = make;
/* Css Not a pure module */
