// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function List(Props) {
  var afterPadding = Props.afterPadding;
  var beforePadding = Props.beforePadding;
  var data = Props.data;
  var identity = Props.identity;
  var onRefChange = Props.onRefChange;
  var renderItem = Props.renderItem;
  return React.createElement("div", {
              className: Css.style(/* :: */[
                    Css.paddingTop(Css.px(beforePadding)),
                    /* :: */[
                      Css.paddingBottom(Css.px(afterPadding)),
                      /* [] */0
                    ]
                  ])
            }, Belt_Array.map(Belt_Array.map(data, (function (item) {
                        return /* tuple */[
                                Curry._1(renderItem, item),
                                Curry._1(identity, item)
                              ];
                      })), (function (itemTuple) {
                    var id = itemTuple[1];
                    return React.cloneElement(itemTuple[0], {
                                ref: (function (elementRef) {
                                    return Curry._2(onRefChange, id, elementRef);
                                  })
                              });
                  })));
}

var make = List;

exports.make = make;
/* Css Not a pure module */
