// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Belt_SortArray = require("bs-platform/lib/js/belt_SortArray.js");
var Belt_HashMapInt = require("bs-platform/lib/js/belt_HashMapInt.js");
var List$ReactHooksTemplate = require("./List.bs.js");

function recsHeight(data, identity, rectangles) {
  return Belt_Option.mapWithDefault(Belt_Option.flatMap(Belt_Option.map(Belt_Array.get(data, data.length - 1 | 0), identity), (function (id) {
                    return Belt_HashMapInt.get(rectangles, id);
                  })), 0, (function (item) {
                return item[/* height */1] + item[/* top */0] | 0;
              }));
}

function heightDelta(data, identity, rectangles, previousRectangles) {
  return recsHeight(data, identity, previousRectangles) - recsHeight(data, identity, rectangles) | 0;
}

function calculateHeight(elementRef, heightMap, id) {
  Belt_Option.map(Belt_Option.map((elementRef == null) ? undefined : Caml_option.some(elementRef), (function (prim) {
              return prim.clientHeight;
            })), (function (height) {
          return Belt_HashMapInt.set(heightMap.current, id, height);
        }));
  return /* () */0;
}

function scrollTop(prim) {
  return prim.scrollTop;
}

function log(prim) {
  console.log(prim);
  return /* () */0;
}

function sortByKey(a, b) {
  var id_b = b[0];
  var id_a = a[0];
  var match = Caml_obj.caml_greaterthan(id_a, id_b);
  if (match) {
    return 1;
  } else if (id_a === id_b) {
    return 0;
  } else {
    return -1;
  }
}

var defaultPositionValue_001 = /* heightMap */Belt_HashMapInt.make(100);

var defaultPositionValue = /* record */[
  /* scrollPosition */15000,
  defaultPositionValue_001
];

function isBetween(target, beginning, endValue) {
  if (Caml_obj.caml_greaterequal(target, beginning)) {
    return Caml_obj.caml_lessequal(target, endValue);
  } else {
    return false;
  }
}

function doesIntersectWith(a, b) {
  if (isBetween(a[/* top */0], b[/* top */0], b[/* top */0] + b[/* height */1] | 0)) {
    return true;
  } else {
    return isBetween(b[/* top */0], a[/* top */0], a[/* top */0] + a[/* height */1] | 0);
  }
}

function createNewRecs(heightMap, identity, defaultHeight, data) {
  var recs = Belt_HashMapInt.make(100);
  var currentHeight = /* record */[/* contents */0];
  var convertToSortedArray = function (heightMap) {
    var map = heightMap.current;
    return Belt_SortArray.stableSortBy(Belt_Array.map(Belt_Array.map(data, (function (item) {
                          var id = Curry._1(identity, item);
                          return /* tuple */[
                                  id,
                                  defaultHeight
                                ];
                        })), (function (item) {
                      var id = item[0];
                      return Belt_Option.mapWithDefault(Belt_HashMapInt.get(map, id), item, (function (measuredHeight) {
                                    return /* tuple */[
                                            id,
                                            measuredHeight
                                          ];
                                  }));
                    })), sortByKey);
  };
  Belt_Array.forEach(convertToSortedArray(heightMap), (function (item) {
          var height = item[1];
          Belt_HashMapInt.set(recs, item[0], /* record */[
                /* top */currentHeight[0],
                /* height */height
              ]);
          currentHeight[0] = currentHeight[0] + height | 0;
          return /* () */0;
        }));
  return recs;
}

function VirtualizedList(Props) {
  var match = Props.bufferCount;
  var bufferCount = match !== undefined ? match : 5;
  var match$1 = Props.defaultPosition;
  var defaultPosition = match$1 !== undefined ? match$1 : defaultPositionValue;
  var onDestroy = Props.onDestroy;
  var match$2 = Props.defaultHeight;
  var defaultHeight = match$2 !== undefined ? match$2 : 200;
  var data = Props.data;
  var identity = Props.identity;
  var viewPortRef = Props.viewPortRef;
  var renderItem = Props.renderItem;
  var match$3 = React.useState((function () {
          return /* record */[
                  /* startIndex */-1,
                  /* endIndex */10
                ];
        }));
  var setIndex = match$3[1];
  var match$4 = match$3[0];
  var endIndex = match$4[/* endIndex */1];
  var startIndex = match$4[/* startIndex */0];
  var match$5 = React.useState((function () {
          return 0;
        }));
  var setCorrection = match$5[1];
  var refMap = React.useRef(Belt_HashMapInt.make(100));
  var heightMap = React.useRef(defaultPosition[/* heightMap */1]);
  var recMap = React.useRef(Belt_HashMapInt.make(100));
  var scrollTopPosition = React.useRef(0);
  var viewPortRec = React.useRef(/* record */[
        /* top */0,
        /* height */0
      ]);
  var prevViewPortRec = React.useRef(/* record */[
        /* top */0,
        /* height */0
      ]);
  var previousSnapshot = React.useRef(/* record */[
        /* rectangles */Belt_HashMapInt.make(100),
        /* startIndex */0,
        /* endIndex */0,
        /* scrollTop */0,
        /* heightMap */Belt_HashMapInt.make(100)
      ]);
  var element = Belt_Option.map(Caml_option.nullable_to_opt(viewPortRef.current), (function (prim) {
          return prim;
        }));
  var handleScroll = function (_e) {
    if (element !== undefined) {
      var element$1 = Caml_option.valFromOption(element);
      var startItem = Belt_Array.reduce(Belt_Array.map(data, (function (rawData) {
                  return Belt_Option.mapWithDefault(Belt_HashMapInt.get(recMap.current, Curry._1(identity, rawData)), /* tuple */[
                              Curry._1(identity, rawData),
                              /* record */[
                                /* top */0,
                                /* height */0
                              ]
                            ], (function (rectangle) {
                                return /* tuple */[
                                        Curry._1(identity, rawData),
                                        rectangle
                                      ];
                              }));
                })), /* tuple */[
            0,
            /* record */[
              /* top */0,
              /* height */0
            ]
          ], (function (sum, item) {
              var sumRect = sum[1];
              var yy = viewPortRec.current;
              var match = (sumRect[/* top */0] + sumRect[/* height */1] | 0) > yy[/* top */0];
              if (match) {
                return sum;
              } else {
                return item;
              }
            }));
      var endItem = Belt_Array.reduce(Belt_Array.map(data, (function (i) {
                  var match = Belt_HashMapInt.get(recMap.current, Curry._1(identity, i));
                  if (match !== undefined) {
                    return /* tuple */[
                            Curry._1(identity, i),
                            match
                          ];
                  } else {
                    return /* tuple */[
                            Curry._1(identity, i),
                            /* record */[
                              /* top */0,
                              /* height */0
                            ]
                          ];
                  }
                })), /* tuple */[
            0,
            /* record */[
              /* top */0,
              /* height */0
            ]
          ], (function (sum, item) {
              var yy = viewPortRec.current;
              var match = (yy[/* top */0] + yy[/* height */1] | 0) <= sum[1][/* top */0];
              if (match) {
                return sum;
              } else {
                return item;
              }
            }));
      Curry._1(setIndex, (function (_prev) {
              var init = previousSnapshot.current;
              previousSnapshot.current = /* record */[
                /* rectangles */init[/* rectangles */0],
                /* startIndex */_prev[/* startIndex */0],
                /* endIndex */init[/* endIndex */2],
                /* scrollTop */init[/* scrollTop */3],
                /* heightMap */init[/* heightMap */4]
              ];
              var init$1 = previousSnapshot.current;
              previousSnapshot.current = /* record */[
                /* rectangles */init$1[/* rectangles */0],
                /* startIndex */init$1[/* startIndex */1],
                /* endIndex */_prev[/* endIndex */1],
                /* scrollTop */element$1.scrollTop | 0,
                /* heightMap */Belt_HashMapInt.copy(heightMap.current)
              ];
              var viewPortReci_000 = /* top */element$1.scrollTop | 0;
              var viewPortReci_001 = /* height */element$1.clientHeight;
              var viewPortReci = /* record */[
                viewPortReci_000,
                viewPortReci_001
              ];
              prevViewPortRec.current = viewPortRec.current;
              viewPortRec.current = viewPortReci;
              var eid = endItem[0];
              var sid = startItem[0];
              var match = (sid - bufferCount | 0) < 0;
              var match$1 = _prev[/* startIndex */0] === (
                match ? 0 : sid - bufferCount | 0
              );
              var match$2 = (eid + bufferCount | 0) > data.length;
              var match$3 = _prev[/* endIndex */1] === (
                match$2 ? data.length : eid + bufferCount | 0
              );
              var exit = 0;
              if (match$1 && match$3) {
                return _prev;
              } else {
                exit = 1;
              }
              if (exit === 1) {
                var match$4 = (sid - bufferCount | 0) < 1;
                var match$5 = (eid + bufferCount | 0) > data.length;
                return /* record */[
                        /* startIndex */match$4 ? 1 : sid - bufferCount | 0,
                        /* endIndex */match$5 ? data.length : eid + bufferCount | 0
                      ];
              }
              
            }));
    }
    Curry._1(setCorrection, (function (x) {
            return x + 1 | 0;
          }));
    return /* () */0;
  };
  React.useEffect((function () {
          setTimeout((function (param) {
                  return Curry._1(setIndex, (function (prev) {
                                return /* record */[
                                        /* startIndex */0,
                                        /* endIndex */prev[/* endIndex */1]
                                      ];
                              }));
                }), 1);
          return undefined;
        }), /* array */[]);
  React.useEffect((function () {
          setTimeout((function (param) {
                  var setScrollTop = Belt_Option.map(Belt_Option.map(Caml_option.nullable_to_opt(viewPortRef.current), (function (prim) {
                              return prim;
                            })), (function (prim, prim$1) {
                          prim.scrollTop = prim$1;
                          return /* () */0;
                        }));
                  if (setScrollTop !== undefined) {
                    return Curry._1(setScrollTop, 15000);
                  } else {
                    return /* () */0;
                  }
                }), 1000);
          return undefined;
        }), /* array */[]);
  React.useEffect((function () {
          if (element !== undefined) {
            Caml_option.valFromOption(element).addEventListener("scroll", handleScroll);
          }
          return (function (param) {
                    if (element !== undefined) {
                      Caml_option.valFromOption(element).removeEventListener("scroll", handleScroll);
                      return /* () */0;
                    } else {
                      return /* () */0;
                    }
                  });
        }), /* array */[element]);
  React.useEffect((function () {
          return (function (param) {
                    return Curry._2(onDestroy, scrollTopPosition.current, heightMap.current);
                  });
        }), /* array */[]);
  React.useEffect((function () {
          var prevRec = Belt_HashMapInt.copy(recMap.current);
          Belt_HashMapInt.forEach(refMap.current, (function (key, item) {
                  return calculateHeight(item, heightMap, key);
                }));
          var recs = createNewRecs(heightMap, identity, defaultHeight, data);
          recMap.current = recs;
          var findAnchor = function (param) {
            var prev = previousSnapshot.current;
            var both = Belt_Array.keep(data, (function (item) {
                    var id = Curry._1(identity, item);
                    var match = prev[/* startIndex */1] <= id && prev[/* endIndex */2] >= id && startIndex <= id && endIndex >= id;
                    if (match) {
                      return true;
                    } else {
                      return false;
                    }
                  }));
            var partial_arg = prevViewPortRec.current;
            var interSectWithPrevViewPortPosition = function (param) {
              return doesIntersectWith(partial_arg, param);
            };
            var anchor = Belt_Array.reduce(Belt_Array.map(both, (function (item) {
                        return Belt_Option.mapWithDefault(Belt_HashMapInt.get(prevRec, Curry._1(identity, item)), /* tuple */[
                                    Curry._1(identity, item),
                                    /* record */[
                                      /* top */0,
                                      /* height */0
                                    ]
                                  ], (function (rectangle) {
                                      return /* tuple */[
                                              Curry._1(identity, item),
                                              rectangle
                                            ];
                                    }));
                      })), /* tuple */[
                  0,
                  /* record */[
                    /* top */0,
                    /* height */0
                  ]
                ], (function (best, current) {
                    var match = Curry._1(interSectWithPrevViewPortPosition, current[1]) && !Curry._1(interSectWithPrevViewPortPosition, best[1]);
                    if (match) {
                      return current;
                    } else {
                      return best;
                    }
                  }));
            var currentAnchorRectangle = Belt_Option.mapWithDefault(Belt_HashMapInt.get(recs, anchor[0]), /* record */[
                  /* top */0,
                  /* height */0
                ], (function (x) {
                    return x;
                  }));
            var correction = currentAnchorRectangle[/* top */0] - anchor[1][/* top */0] | 0;
            var match = correction > 0;
            if (element !== undefined && match) {
              Caml_option.valFromOption(element).scrollBy({
                    top: correction,
                    left: 0.0,
                    behavior: "auto"
                  });
              return /* () */0;
            } else {
              return /* () */0;
            }
          };
          var match = heightDelta(data, identity, recs, prevRec) === 0;
          if (!match) {
            findAnchor(/* () */0);
          }
          return undefined;
        }), /* array */[
        startIndex,
        endIndex
      ]);
  var startPadding = Belt_Option.mapWithDefault(Belt_HashMapInt.get(recMap.current, startIndex), 0, (function (x) {
          return x[/* top */0];
        }));
  var endValue = Belt_Option.mapWithDefault(Belt_HashMapInt.get(recMap.current, endIndex), 0, (function (x) {
          return x[/* top */0];
        }));
  var lastValue = Belt_Option.mapWithDefault(Belt_HashMapInt.get(recMap.current, Belt_HashMapInt.size(recMap.current)), 0, (function (x) {
          return x[/* top */0];
        }));
  var endPadding = lastValue - endValue | 0;
  return React.createElement(List$ReactHooksTemplate.make, {
              afterPadding: endPadding,
              beforePadding: startPadding,
              data: Belt_Array.keep(data, (function (item) {
                      if (Curry._1(identity, item) <= endIndex) {
                        return Curry._1(identity, item) >= startIndex;
                      } else {
                        return false;
                      }
                    })),
              identity: identity,
              onRefChange: (function (id, elementRef) {
                  return Belt_HashMapInt.set(refMap.current, id, elementRef);
                }),
              renderItem: renderItem
            });
}

var make = VirtualizedList;

exports.recsHeight = recsHeight;
exports.heightDelta = heightDelta;
exports.calculateHeight = calculateHeight;
exports.scrollTop = scrollTop;
exports.log = log;
exports.sortByKey = sortByKey;
exports.defaultPositionValue = defaultPositionValue;
exports.isBetween = isBetween;
exports.doesIntersectWith = doesIntersectWith;
exports.createNewRecs = createNewRecs;
exports.make = make;
/* defaultPositionValue Not a pure module */
