// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Item$ReactHooksTemplate = require("./components/Item/Item.bs.js");
var VirtualizedList$ReactHooksTemplate = require("./containers/VirtualizedList/VirtualizedList.bs.js");

var data = Belt_Array.map(Belt_Array.range(0, 100), (function (id) {
        return /* record */[
                /* id */id,
                /* sampleString */String(id)
              ];
      }));

function App(Props) {
  var testRef = React.useRef(null);
  return React.createElement("div", undefined, React.createElement(VirtualizedList$ReactHooksTemplate.make, {
                  data: data,
                  renderItem: (function (data) {
                      return React.createElement(Item$ReactHooksTemplate.make, {
                                  id: data[/* id */0],
                                  key: String(data[/* id */0]),
                                  ref: testRef
                                });
                    }),
                  identity: (function (data) {
                      return data[/* id */0];
                    })
                }));
}

var make = App;

exports.data = data;
exports.make = make;
/* data Not a pure module */
